rifflearning/jitsi-meet

react/features/riff-metrics/sass/main.scss
=> style fix, icon connection status

Makefile, deploy-aws.sh
Added deployment script for uploading front-end changes to the jitsi aws instance.
=> add deployment script

react/features/riff-dashboard-page/src/components/NavBar/NavBarView.js, react/features/riff-dashboard-page/src/sass/jitsi-theme-overrides.scss, react/features/riff-dashboard-page/src/sass/main.scss
Added jitsi theme style overrides for dashboard page, replaced logo.
=> add jitsi theme style overrides for dashboard page

css/main.scss, package-lock.json, package.json, react/features/conference/components/web/Conference.js
=> add draggable MeetinMediator

package-lock.json, package.json
=> deps: lib-jitsi-meet@latest

README.md, deploy-aws.sh
=> Add documentation jitsi-meet deployment in aws

conference.js, react/features/riff-dashboard-page/actions.js, react/features/riff-dashboard-page/nodejs-browser-stats.js
=> add browser network stats

css/main.scss, react/features/conference/components/web/Conference.js
=> make meeting medator draggable outside of the viewport

css/riff-styles.scss, react/features/riff-platform/components/DraggableMeetingMediator/index.js
=> make meeting mediator collapse

react/features/riff-platform/components/Meetings/MeetingTabPanel.js, react/features/riff-platform/components/Meetings/index.js
=> fix meeting list spacing

react/features/riff-platform/components/Meetings/index.js
=> fix disabling delete button for separate group

react/features/riff-platform/components/Meetings/MeetingTabPanel.js, react/features/riff-platform/components/Meetings/index.js
=> change tabs text color to white

react/features/riff-platform/components/Meetings/MeetingRow.js, react/features/riff-platform/components/Scheduler/SchedulerForm.js, react/features/riff-platform/functions.js
=> change multiple rooms meeting logic

react/features/riff-platform/actions/meeting.js, react/features/riff-platform/api.js, react/features/riff-platform/components/Meetings/MeetingRow.js, react/features/riff-platform/components/Scheduler/ScheduleSuccess.js
=> fetchMeetingByRoomId instead of _id, same link for recurring

react/features/chat/components/web/ChatMessage.js, react/features/speaker-stats/components/SpeakerStats.js
=> maybeExtractIdFromDisplayName for chats and spekerStats

react/features/conference/components/web/Subject.js
=> always turned on top toolbar

react/features/riff-platform/actions/jitsiActions.js
=> set TileView After YoutubeSharing

react/features/riff-platform/components/Main.js, react/features/riff-platform/components/Meetings/MeetingRow.js, react/features/riff-platform/components/Scheduler/SchedulerForm.js
- fixed meetings negotiations list;
- fixed schedule cancel button error;
- added 'Copy Link' button to meeting row;
=> Fix meetings negotiations

css/riff-styles.scss
=> fix mediator visibility

react/features/base/devices/middleware.js, react/features/riff-platform/actions/sibilantActions.js
=> fix attach sibilant onchange audio input

react/features/riff-platform/actions/jitsiActions.js, react/features/riff-platform/actions/sibilantActions.js, react/features/riff-platform/components/App.js, react/features/riff-platform/components/MeetingEndedPage.js
=> Integration mattermost

react/features/riff-platform/components/EditMeeting/index.js, react/features/riff-platform/components/Meeting/index.js, react/features/riff-platform/components/Scheduler/SchedulerForm.js
=> Feature/fix schedule err 'no meeting with ID'

react/features/riff-platform/actions/jitsiActions.js
=> if anon user, redirect to login after meeting

README.md, RIFF_DEVNOTES.md
=> add dev notes

react/features/riff-platform/actions/meeting.js
The meeting roomId is stored with the room number for the conference 
Issue: https://riffanalytics.atlassian.net/browse/ODIN-188
Create a meeting with multiple rooms and check meeting mediator
- ✅ Bug fix (non-breaking change which fixes an issue)
=> store the current roomId with the selected room number

react/features/riff-platform/components/DraggableMeetingMediator/MeetingMediator.js, react/features/riff-platform/components/DraggableMeetingMediator/index.js, react/features/riff-platform/libs/charts.js
Use the meeting mediator from [@rifflearning/riff-metrics](https://github.com/rifflearning/riff-metrics)
The meeting mediator was broken
- ✅ Bug fix (non-breaking change which fixes an issue)
=> import MM from @rifflearning/riff-metrics

react/features/riff-platform/components/LocalRecorder/WebmAdapter.js
Fix filtering available participants audio streams
Issue [RIFF-392](https://riffanalytics.atlassian.net/browse/RIFF-392)
1. Joined to the conference with unmuted microphone;
2. Joined the conference as another participant with muted microphone; 
3. Started local recording by the participant with unmuted microphone;
- ✅ Bug fix (non-breaking change which fixes an issue)
=> fix bug when the audio-muted user joins the meeting

react/features/riff-platform/components/Meeting/index.js, react/features/riff-platform/components/Scheduler/SchedulerForm.js, react/features/riff-platform/docs/SCHEDULERDEVNOTES.md
Made "Allow anonymous users" on by default on the schedule form. Renamed 'anonymous' as 'guest'
[RIFF-360](https://riffanalytics.atlassian.net/browse/RIFF-360)
- ✅ New feature (non-breaking change which adds functionality))
- ✅ My change requires a change to the documentation and I have updated it accordingly.
=> allow anonymous users on by default; rename anonymous as guest

react/features/riff-platform/actions/sibilantActions.js, react/features/toolbox/components/HangupButton.js
**General**
This PR fixes the bug outlined in RIFF-549 where closing a meeting's tab rather than pressing the hangup button would not register that the user left the meeting, thereby causing the meeting's end time to be set incorrectly (i.e. the meeting's end time would be 10min later than it actually was).  
**HangupButton**
The hangup button now has an `onUnload()` event handler which calls `participantLeaveRoom()` from sibilant actions. Furthermore, an event listener for `onUnload()` is added in `componentDidMount()` and removed in `componentWillUnmount()`. Additionally, props for the component (i.e. the meetingId and participantId) are now available for use by `participantLeaveRoom()`.
**SibilantActions**
Since `participantLeaveRoom()` requires the meetingId in order to work, a change …
=> BugFix: End Time Is Now Correct (RIFF-549)

react/features/google-api/constants.js
For Riff google calendar implementation only calendar events scope is requested, all calendar scope is not needed.
For google app verification requested scope must be as granular as possible
I`ve tested locally.
- ✅ Maintenance (change which doesn't modify functionality, but provides dependency updates or tooling improvements)
=> Update google calendar auth scope
